### ISSUE TITLE
Do not import names if already present

### ISSUE THREAD

**Issue by dkosteck** [redhat-eets/glpi-helper-scripts#25]
Users changing names in GLPI will be bulldozed by subsequent runs, we need to handle this

**Comment by adhil0** [comment]
Maybe this could be an optional flag passed in at runtime?

**Comment by dkosteck** [comment]
Steps:

- Create a argparse field for overwriting name
- Check if name is present, if so, only overwrite if flag is set

**Comment by ericz2002** [comment]
https://github.com/redhat-eets/glpi-helper-scripts/pull/33
