### ISSUE TITLE
GLPI IP and Token should be settable in the environment

### ISSUE THREAD

**Issue by lack** [redhat-eets/glpi-helper-scripts#9]
Rather than having to add my instance IP and token to the commandline every time, it would be more convenient (and more secure, in the case of the token) to have the scripts look for these values in the environment instead; maybe `$GLPI_INSTANCE` and `$GLPI_TOKEN` for example?

**Comment by ericz2002** [comment]
https://github.com/redhat-eets/glpi-helper-scripts/pull/28
